In [2]:
import numpy as np

# Problem Statement:

You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
use the NumPy package and do some tasks related to that.

# Tasks To Be Performed:

1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [5]:
arr_1 = np.arange(2, 11).reshape((3, 3))
arr_1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

or

In [7]:
arr_1 = np.resize(np.arange(2, 11), (3,3))
arr_1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. Create a NumPy array having user input values and convert the integer type to the float type of the elements of the array.  
For instance: Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [8]:
list_store  = []
while True:
    try:
        user_input = input("Enter integers for the list(press q to quit): ")
        if user_input == 'q':
            break
        user_input = int(user_input)
    except ValueError:
        print("Error: Please enter integers only.")
    except Exception as e:
        print(f"Error: {e}")
    else:
        list_store.append(user_input)
        
Original_array = np.array(list_store)

Float_Array = np.array(Original_array, dtype = np.float64)

print("Original Array: ", Original_array)
print("Float Array: ", Float_Array)

Enter integers for the list(press q to quit): 1.0
Error: Please enter integers only.
Enter integers for the list(press q to quit): 1
Enter integers for the list(press q to quit): 2
Enter integers for the list(press q to quit): 3
Enter integers for the list(press q to quit): 4
Enter integers for the list(press q to quit): q
Original Array:  [1 2 3 4]
Float Array:  [1. 2. 3. 4.]


3. Write a NumPy program to append values to the end of an array.  
For instance: Original array: [10, 20, 30] . After that, append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [19]:
Original_array = np.array([10, 20, 30])
print("Original array: ", Original_array)
Append_array = np.linspace(40, 90, 6, dtype = int)
Original_array = np.concatenate([Original_array, Append_array], axis = 0)
print("Array after appending: ",Original_array)

Original array:  [10 20 30]
Array after appending:  [10 20 30 40 50 60 70 80 90]


or

In [13]:
Original_array = np.array([10, 20, 30])
print("Original array: ", Original_array)
Append_array = np.linspace(40, 90, 6, dtype = int)
Original_array = np.hstack([Original_array, Append_array])
print("Array after appending: ",Original_array)

Original array:  [10 20 30]
Array after appending:  [10 20 30 40 50 60 70 80 90]


or

In [14]:
Original_array = np.array([10, 20, 30])
print("Original array: ", Original_array)
Append_array = np.linspace(40, 90, 6, dtype = int)
Original_array = np.append(Original_array, Append_array, axis = 0)
print("Array after appending: ",Original_array)

Original array:  [10 20 30]
Array after appending:  [10 20 30 40 50 60 70 80 90]


4. Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray.

In [18]:
#assuming element wise addition
a = np.array([1,2,3])
b = np.array([4,5,6])
sumArray = np.add(a,b)
print(f"Sum of {a = } and {b = } is {sumArray}")

Sum of a = array([1, 2, 3]) and b = array([4, 5, 6]) is [5 7 9]


or

In [22]:
#assuming addition of all element from both arrays is required
a = np.array([1,2,3])
b = np.array([4,5,6])
sumArray = np.sum(a) + np.sum(b)
print(f"Sum of {a = } and {b = } is {sumArray}")

Sum of a = array([1, 2, 3]) and b = array([4, 5, 6]) is 21


5. Create a 3x3 array having values from 10-90 (interval of 10) and store that in array1  
Perform the following tasks:  
a. Extract the 1st row from the array  
b. Extract the last element from the array

In [20]:
array1 = np.arange(10, 90, 9).reshape((3, 3))
print(f"The first row of array {array1} is {array1[0]}")
print(f"The last element of array {array1} is {array1[-1][-1]}")

The first row of array [[10 19 28]
 [37 46 55]
 [64 73 82]] is [10 19 28]
The last element of array [[10 19 28]
 [37 46 55]
 [64 73 82]] is 82
