In [1]:
import numpy as np

# Problem Statement:

You work in XYZ Company as a Python developer. The company officials want
you to build a Python program.

# Tasks To Be Performed:

1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric value and returns a NumPy array of the given dimension filled with the
given value  
e.g.: solve((3, 3), 5) will return  
[[5, 5, 5],  
[5, 5, 5],  
[5, 5, 5]]

In [6]:
def return_fill_array(dim, val):
    return np.full(dim, val)

while True:
    try:
        dim_input = eval(input("Enter the dimension in form of a tuple: "))
        dim_list = []
        assert type(dim_input) == tuple, 'The input doesnt look like a tuple'
        for elem in dim_input:
            assert elem > 0 and int(elem) == elem, 'Dimensions should be integer only and greater than zero'
            dim_list.append(int(elem))
        dim_input = tuple(dim_list)
        del dim_list
    except (ValueError, NameError) as e:
        print("Error: Please enter tuple only with elements as integers greater than zero.")
    except Exception as e:
        print(f"Error: {e}")
    else:
        break

while True:
    try:
        value_input = float(input("Enter numeric value: "))
        if int(value_input) == value_input:
            value_input = int(value_input)
    except ValueError as e:
        print("Error: Please enter numeric values only.")
    except Exception as e:
        print(f"Error: {e}")
    else:
        break
        
print("Array is: ", return_fill_array(dim_input, value_input))

Enter the dimension in form of a tuple: (1.0,2,3)
Enter numeric value: 5.5
Array is:  [[[5.5 5.5 5.5]
  [5.5 5.5 5.5]]]


2. Create a method that takes n NumPy arrays of the same dimensions, sums them and returns the answer.

In [16]:
#assuming by dimension in question it means shape
#assuming the input to function will be one integer indicating number of arrays followed by the arrays
def sum_array(n, *args):
    try:
        if n == 0:
            raise Exception("The number of arrays should be greater than zero")
        elif len(args) != n:
            raise Exception(f"The number of arrays don't match as {n = } and no. of arrays = {len(args)}")
        else:
            shape = args[0].shape
            for arr in args:
                if arr.shape != shape:
                    raise Exception("The shapes of given arrays don't match")
        sumArray = np.zeros(shape)
        for arr in args:
            np.add(sumArray, arr, out = sumArray)
    except Exception as e:
        print(f"Error: {e}")
    else:
        return sumArray

In [21]:
sum_array(2, np.array([1, 23, 4]), np.array([1, 2, 3]))

array([ 2., 25.,  7.])

In [22]:
sum_array(2)

Error: The number of arrays don't match as n = 2 and no. of arrays = 0


3. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:  
[[1, 2, 3],  
[4, 5, 6],  
[7, 8, 9]]  
top_left_sub_matrix (matrix, 2, 2) -> should return:  
[[1, 2]  
[4, 5]]

In [33]:
#assuming inputs will be proper
def return_top_left(arr, N, M):
    row, col = arr.shape
    if N <= 0 or M <= 0:
        print("Requested dimensions can't be negative")
    elif N > row or M > col:
        print(f"Unable to find top-left {N} X {M} matrix as given array's shape is {row} X {col}")
    else:
        return arr[:N, :M]

In [34]:
return_top_left(np.array([[1,2,3]]), 2, 2)

Unable to find top-left 2 X 2 matrix as given array's shape is 1 X 3


4. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the
bottom-right N X M sub matrix, e.g:  
[[1, 2, 3],  
[4, 5, 6],  
[7, 8, 9]]  
sub_matrix(matrix, 2, 2) -> should return : (Keep in mind these arrays are zero indexed)  
[[5, 6]  
[8, 9]]  

In [48]:
#assuming inputs will be proper
def sub_matrix(arr, N, M):
    row, col = arr.shape
    if N <= 0 or M <= 0:
        print("Requested dimensions can't be negative")
    elif N > row or M > col:
        print(f"Unable to find bottom-right {N} X {M} matrix as given array's shape is {row} X {col}")
    else:
        return arr[-N:, -M:]

In [49]:
sub_matrix(np.array([[1,2,3],[4,5,6],[7,8,9]]), 2, 2)

array([[5, 6],
       [8, 9]])

5. Given a 1 D NumPy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as values:  
[1, 1, 1]  
solution(arr) -> should return :  
{'mean': 1.0, 'std_dev': 0.0}

In [44]:
#assuming input will be proper
def solution(arr):
    return {'mean': np.mean(arr, axis = 0), 'std_dev': np.std(arr, axis = 0)}

In [46]:
solution(np.array([1,4,7,10,0,-1]))

{'mean': 3.5, 'std_dev': 3.947573094109004}

In [47]:
solution(np.array([1,1,1]))

{'mean': 1.0, 'std_dev': 0.0}