In [1]:
import numpy as np

In [15]:
np.zeros((2, 3)) # using built-in zeros function

array([[0., 0., 0.],
       [0., 0., 0.]])

or

In [14]:
np.full((2, 3), 0) # using full function

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
np.concatenate([arr], axis= None) # using concatenate

array([1, 2, 3, 4, 5, 6])

or

In [5]:
np.ravel(arr) # using ravel function

array([1, 2, 3, 4, 5, 6])

In [6]:
arr = np.array([1,2,3,4,5,6])
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

or

In [7]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

or

In [8]:
arr.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

or

In [9]:
arr.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
arr = np.array([1, 3, 2, 6, 5, 4])

In [11]:
np.sort(arr) # sorted copy return

array([1, 2, 3, 4, 5, 6])

In [13]:
arr.sort()
print(arr) # sorted in place

[1 2 3 4 5 6]
