In [1]:
import numpy as np

# Problem Statement:

Numpy library package from python is one of the most useful while conducting any statistical
analysis in data science. Familiarize yourself with the nitty gritties of the numpy and various
modules that it comes with.

# Tasks to be Performed:

1. Given two numpy arrays A and B that have values [1,2,3,4] and [5,6,7,8] respectively.  
Perform the following operations.  
a. Add the two arrays  
b. Subtract the two arrays  
c. Multiply the two arrays:  
i. With 5  
ii. With each other.  
d. Divide the two arrays:  
i. By 2  
ii. Divide A with B  
iii. Divide B with A.

In [2]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

In [3]:
np.add(A, B)

array([ 6,  8, 10, 12])

In [4]:
np.subtract(A, B)

array([-4, -4, -4, -4])

In [5]:
np.multiply(A, 5)

array([ 5, 10, 15, 20])

In [6]:
np.multiply(A, B)

array([ 5, 12, 21, 32])

In [7]:
np.divide(A, 2)

array([0.5, 1. , 1.5, 2. ])

In [8]:
np.divide(A, B)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [9]:
np.divide(B, A)

array([5.        , 3.        , 2.33333333, 2.        ])

2. For the given two arrays A and B.  
A = np.array([[2,9],[6,13]])  
B = np.array([[1,4],[3,11]])  
Perform the following operations,  
a. Cross product of A and B.  
b. Dot product of A and B.  
c. Matrix multiplication of A and B.  
d. Square root of A and B.

In [58]:
A = np.array([[2,9],[6,13]])  
B = np.array([[1,4],[3,11]]) 

In [59]:
np.cross(A, B, axisa = 1, axisb = 1)

array([-1, 27])

In [60]:
np.dot(A, B)

array([[ 29, 107],
       [ 45, 167]])

In [61]:
np.matmul(A, B)

array([[ 29, 107],
       [ 45, 167]])

In [62]:
np.sqrt(A)

array([[1.41421356, 3.        ],
       [2.44948974, 3.60555128]])

In [63]:
np.sqrt(B)

array([[1.        , 2.        ],
       [1.73205081, 3.31662479]])

3. Create a 3x3 matrix with random values, flatten the array with the reshape() method and
print the shape of the flattened array and the resultant array.

In [10]:
arr_2d = np.random.random((3, 3))
arr_2d_flattened = np.reshape(arr_2d, (9,))
print("Shape of resultant array: ", arr_2d.shape)
print("Shape of flattened array: ", arr_2d_flattened.shape)

Shape of resultant array:  (3, 3)
Shape of flattened array:  (9,)


4. Create an array that will have days from an entire year in the datetime format using the
datetime64 numpy method.

In [12]:
#assuming year 2023, so 365 days
datediff = np.arange(0, 365)
initial_date = np.datetime64('2023-01-01')
dates = datediff + initial_date
print(dates)

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31' '2023-02-01' '2023-02-02' '2023-02-03' '2023-02-04'
 '2023-02-05' '2023-02-06' '2023-02-07' '2023-02-08' '2023-02-09'
 '2023-02-10' '2023-02-11' '2023-02-12' '2023-02-13' '2023-02-14'
 '2023-02-15' '2023-02-16' '2023-02-17' '2023-02-18' '2023-02-19'
 '2023-02-20' '2023-02-21' '2023-02-22' '2023-02-23' '2023-02-24'
 '2023-02-25' '2023-02-26' '2023-02-27' '2023-02-28' '2023-03-01'
 '2023-03-02' '2023-03-03' '2023-03-04' '2023-03-05' '2023-03-06'
 '2023-03-07' '2023-03-08' '2023-03-09' '2023-03-10' '2023-03-11'
 '2023-03-12' '2023-03-13' '2023-03-14' '2023-03-15' '2023-03-16'
 '2023-03-

5. Given two arrays A and B, perform the following operations  
A = np.array([[2,3],[6,4]])  
B = np.array([[3,6],[4,9]])  
a. Horizontal stacking  
b. Vertical Stacking  
c. Row Stacking  
d. Column Stacking  
e. Depth Stacking  
f. Append A to B  
g. Concatenate A and B

In [14]:
A = np.array([[2, 3],[6, 4]])
B = np.array([[3, 6],[4, 9]])

In [15]:
np.hstack([A, B])

array([[2, 3, 3, 6],
       [6, 4, 4, 9]])

In [16]:
np.vstack([A, B])

array([[2, 3],
       [6, 4],
       [3, 6],
       [4, 9]])

In [17]:
np.row_stack([A, B])

array([[2, 3],
       [6, 4],
       [3, 6],
       [4, 9]])

In [18]:
np.column_stack([A, B])

array([[2, 3, 3, 6],
       [6, 4, 4, 9]])

In [19]:
np.dstack([A, B])

array([[[2, 3],
        [3, 6]],

       [[6, 4],
        [4, 9]]])

In [23]:
np.append(B, A, axis = 0)

array([[3, 6],
       [4, 9],
       [2, 3],
       [6, 4]])

In [22]:
np.append(B, A, axis = 1)

array([[3, 6, 2, 3],
       [4, 9, 6, 4]])

In [24]:
np.append(B, A)

array([3, 6, 4, 9, 2, 3, 6, 4])

In [26]:
np.concatenate([A, B], axis = 0)

array([[2, 3],
       [6, 4],
       [3, 6],
       [4, 9]])

In [27]:
np.concatenate([A, B], axis = 1)

array([[2, 3, 3, 6],
       [6, 4, 4, 9]])

In [29]:
np.concatenate([A, B], axis = None)

array([2, 3, 6, 4, 3, 6, 4, 9])

6. Given an array A, perform the following operations  
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15], [16,17,18]])  
a. Horizontal split  
b. Vertical Split  
c. Row Split  
d. Column Split

In [30]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15], [16,17,18]])

In [31]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [32]:
np.hsplit(A, 3)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [33]:
np.hsplit(A, [2])

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [34]:
np.vsplit(A, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [35]:
np.vsplit(A, 6)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [37]:
np.vsplit(A, 2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [39]:
np.vsplit(A, [2, 5])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18]])]

In [40]:
# row split
np.split(A, 3, axis = 0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [41]:
# column split
np.split(A, 3, axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

7. For a given 3x3 matrix, perform the following operations.  
A = np.array([[1,4,7],[3,1,9],[2,8,11]])  
a. Find the rank of the matrix  
b. Find the trace of the matrix  
c. Find the inverse of the matrix  
d. Find the transpose of the matrix  
e. Find the determinant of the matrix  
f. Find the eigenvalues and eigenvectors the matrix

In [48]:
A = np.array([[1,4,7],[3,1,9],[2,8,11]])  

In [49]:
A

array([[ 1,  4,  7],
       [ 3,  1,  9],
       [ 2,  8, 11]])

In [50]:
np.linalg.matrix_rank(A) # rank

3

In [52]:
np.sum(np.diag(A)) # trace

13

In [53]:
A.trace() # trace

13

In [ ]:
np.linalg.inv(A) # inverse

In [54]:
np.transpose(A, [1, 0]) # transpose

array([[ 1,  3,  2],
       [ 4,  1,  8],
       [ 7,  9, 11]])

In [55]:
np.linalg.det(A) # determinant

33.000000000000014

In [57]:
w, v = np.linalg.eig(A) # eigenvalues & eigenvectors
print("Eigen values: ", w)
print("Eigen vectors: ", v)

Eigen values:  [17.41535066 -0.48171173 -3.93363893]
Eigen vectors:  [[-0.44018011 -0.89954986  0.05526996]
 [-0.49219026 -0.26902919 -0.88319891]
 [-0.75099282  0.34414147  0.46573052]]


8. For the given two arrays A and B, find the correlation coefficients.  
A = np.array([[11,17,42],[21,19,27]])  
B = np.array([[12,44,39],[62,81,10]])

In [44]:
A = np.array([[11,17,42],[21,19,27]])  
B = np.array([[12,44,39],[62,81,10]])

In [45]:
np.corrcoef(A, B) # correlation coefficient

array([[ 1.        ,  0.9106039 ,  0.53232532, -0.90264562],
       [ 0.9106039 ,  1.        ,  0.13487934, -0.99982205],
       [ 0.53232532,  0.13487934,  1.        , -0.11616343],
       [-0.90264562, -0.99982205, -0.11616343,  1.        ]])