In [1]:
import numpy as np

# Problem Statement:

Numpy library package from python is one of the most useful while conducting any statistical
analysis in data science. Familiarize yourself with the nitty gritties of the numpy and various
modules that it comes with.

# Tasks To be Performed:

1. Create a numpy array with numpy.array module and with a data type integer and float.

In [2]:
arr_int = np.array([1, 2.1, 3], dtype = np.int32)
arr_float = np.array([1, 2.1, 3], dtype = np.float64)

print("Integer array = ", arr_int)
print("Float array = ", arr_float)

Integer array =  [1 2 3]
Float array =  [1.  2.1 3. ]


2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above.

In [5]:
arr_0 = np.array(10)
print("Array: ", arr_0)
print("Dimension: ", arr_0.ndim)
print("Shape: ", arr_0.shape)

Array:  10
Dimension:  0
Shape:  ()


In [6]:
arr_1 = np.array([1,2,3])
print("Array: ", arr_1)
print("Dimension: ", arr_1.ndim)
print("Shape: ", arr_1.shape)

Array:  [1 2 3]
Dimension:  1
Shape:  (3,)


In [10]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print("Array: \n", arr_2)
print("Dimension: ", arr_2.ndim)
print("Shape: ", arr_2.shape)

Array: 
 [[1 2 3]
 [4 5 6]]
Dimension:  2
Shape:  (2, 3)


In [9]:
arr_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print("Array: \n", arr_3)
print("Dimension: ", arr_3.ndim)
print("Shape: ", arr_3.shape)

Array: 
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
Dimension:  3
Shape:  (2, 2, 3)


In [11]:
arr_4 = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]]])
print("Array: \n", arr_4)
print("Dimension: ", arr_4.ndim)
print("Shape: ", arr_4.shape)

Array: 
 [[[[1 2 3]
   [4 5 6]]

  [[7 8 9]
   [0 1 2]]]]
Dimension:  4
Shape:  (1, 2, 2, 3)


3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.

In [12]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

or

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

or

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [17]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

5. Create a numpy array that has the shape 3x5 and all the elements are 5.

In [18]:
np.full((3, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.

In [19]:
np.random.randint(0, 100, 25)

array([87,  0, 27, 43,  7,  6, 32, 23, 96, 84, 59, 95,  8,  1, 82, 95, 48,
       19, 39, 87, 59, 32, 30, 81, 81])

7. Create a numpy array with a shape 3x3 that has all elements as 1.

In [20]:
np.full((3, 3), 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [24]:
arr = np.random.randint(0, 100, (2, 3))
arr

array([[65, 22, 77],
       [69, 78, 13]])

In [25]:
arr.reshape((3,2))

array([[65, 22],
       [77, 69],
       [78, 13]])

9. Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the following operations on the same.  
a. Print the first ten elements of the array.  
b. Print the last ten elements of the array  
c. Print the elements from the indexes 10-25  
d. Print the element at the index 22  
e. Print the array using negative indexing.  
f. Print the last ten elements of the array, using negative indexing.

In [27]:
arr = np.random.choice(np.arange(0, 1000, 2), 50, replace = False)
arr

array([392, 150,  40, 344, 532, 180, 492, 918, 504, 178, 396, 862, 896,
       338, 324, 274, 358, 960, 800, 930, 900,  98, 924, 676, 528, 948,
       768, 736, 322, 602, 764, 952, 166, 458, 882, 828, 750, 500, 850,
        42, 284, 520, 480, 420, 712, 754, 684, 996, 848, 706])

In [29]:
arr[:10]

array([392, 150,  40, 344, 532, 180, 492, 918, 504, 178])

In [35]:
arr[40:]

array([284, 520, 480, 420, 712, 754, 684, 996, 848, 706])

In [31]:
arr[10:26]

array([396, 862, 896, 338, 324, 274, 358, 960, 800, 930, 900,  98, 924,
       676, 528, 948])

In [32]:
arr[22]

924

In [36]:
arr[-49:]

array([150,  40, 344, 532, 180, 492, 918, 504, 178, 396, 862, 896, 338,
       324, 274, 358, 960, 800, 930, 900,  98, 924, 676, 528, 948, 768,
       736, 322, 602, 764, 952, 166, 458, 882, 828, 750, 500, 850,  42,
       284, 520, 480, 420, 712, 754, 684, 996, 848, 706])

In [37]:
arr[-10:]

array([284, 520, 480, 420, 712, 754, 684, 996, 848, 706])

10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.  
a. Insert the element 6 at the end of the array.  
b. Insert the element 10 at the beginning of the array.  
c. Insert the element 30, before 4.  
d. Update the element 5 as 50.  
e. Delete the element 50 in the updated array.  
f. Create a function to search for the element 30.  
g. Sort the array in ascending order.

In [39]:
arr = np.array([1, 2, 3, 4, 5])

In [40]:
arr = np.append(arr, 6, axis = 0)
arr

array([1, 2, 3, 4, 5, 6])

In [43]:
arr = np.insert(arr, 0, 10, axis = 0)
arr

array([10,  1,  2,  3,  4,  5,  6])

In [44]:
arr = np.insert(arr, 4, 30, axis = 0)
arr

array([10,  1,  2,  3, 30,  4,  5,  6])

In [45]:
arr[-2] = 50
arr

array([10,  1,  2,  3, 30,  4, 50,  6])

In [47]:
arr = np.delete(arr, -2, axis = 0)

In [48]:
arr

array([10,  1,  2,  3, 30,  4,  6])

In [51]:
def search_30(arr):
    return np.where(arr == 30)[0]

In [52]:
search_30(arr)

array([4], dtype=int64)

In [53]:
arr = np.sort(arr, axis = 0)
arr

array([ 1,  2,  3,  4,  6, 10, 30])